# Generated by Django 5.2.8 on 2025-11-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hakkımızda', max_length=150, verbose_name='Başlık')),
                ('hero_title', models.CharField(blank=True, help_text='Sayfanın üst kısmında görünen büyük başlık.', max_length=200, verbose_name='Üst Başlık')),
                ('hero_subtitle', models.CharField(blank=True, help_text='Başlığın altında kısa açıklama.', max_length=255, verbose_name='Alt Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son güncelleme')),
            ],
            options={
                'verbose_name': 'Hakkımızda Sayfası',
                'verbose_name_plural': 'Hakkımızda Sayfası',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('map_iframe', models.TextField(blank=True, help_text='Google Maps embed kodu (opsiyonel).', verbose_name='Harita (iframe)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son güncelleme')),
            ],
            options={
                'verbose_name': 'İletişim Bilgisi',
                'verbose_name_plural': 'İletişim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Proje Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='Müşteri / Kurum')),
                ('summary', models.CharField(max_length=255, verbose_name='Kısa Özet')),
                ('description', models.TextField(blank=True, verbose_name='Detay Açıklama')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Anasayfada Göster')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Hizmet Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('short_description', models.CharField(max_length=255, verbose_name='Kısa Açıklama')),
                ('description', models.TextField(blank=True, verbose_name='Detay Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order', 'title'],
            },
        ),
    ]
