# Generated by Django 5.2.8 on 2026-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Kart Başlığı')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Kısa Açıklama')),
                ('image', models.FileField(upload_to='home/service_cards/', verbose_name='Görsel')),
                ('link_url', models.CharField(blank=True, help_text='Örn: /hizmetler/cografi-bilgi-sistemleri/', max_length=220, verbose_name='Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son güncelleme')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Hizmet Kartı',
                'verbose_name_plural': 'Ana Sayfa Hizmet Kartları',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Slider Başlığı')),
                ('subtitle', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.FileField(upload_to='home/slides/', verbose_name='Görsel')),
                ('button_text', models.CharField(default='DETAYLAR', max_length=40, verbose_name='Buton Yazısı')),
                ('button_url', models.CharField(blank=True, help_text='Örn: /hizmetler/siber-guvenlik-sistemleri/', max_length=220, verbose_name='Buton Linki')),
                ('second_button_text', models.CharField(blank=True, max_length=50, verbose_name='İkinci Buton Yazısı')),
                ('second_button_url', models.CharField(blank=True, max_length=220, verbose_name='İkinci Buton Linki')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son güncelleme')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Slider',
                'verbose_name_plural': 'Ana Sayfa Slider',
                'ordering': ['order', 'title'],
            },
        ),
    ]
