# Generated by Django 5.2.8 on 2026-05-07 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_homeservicecard_homeslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Başlık')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Anahtarı')),
                ('path', models.CharField(help_text='Örn: /hakkimizda/ veya /hizmetler/siber-guvenlik-sistemleri/', max_length=220, unique=True, verbose_name='Sayfa Yolu')),
                ('page_type', models.CharField(choices=[('page', 'Sayfa'), ('service', 'Hizmet Detay'), ('project', 'Proje Detay')], default='page', max_length=20, verbose_name='Sayfa Türü')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='Küçük Üst Başlık')),
                ('summary', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('hero_image', models.FileField(blank=True, upload_to='pages/hero/', verbose_name='Üst Görsel')),
                ('body', models.TextField(blank=True, verbose_name='Ana İçerik')),
                ('primary_button_text', models.CharField(blank=True, max_length=50, verbose_name='Ana Buton Yazısı')),
                ('primary_button_url', models.CharField(blank=True, max_length=220, verbose_name='Ana Buton Linki')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son güncelleme')),
            ],
            options={
                'verbose_name': 'Yönetilebilir Sayfa',
                'verbose_name_plural': 'Yönetilebilir Sayfalar',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ManagedPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Bölüm Başlığı')),
                ('content', models.TextField(blank=True, verbose_name='Bölüm İçeriği')),
                ('image', models.FileField(blank=True, upload_to='pages/sections/', verbose_name='Bölüm Görseli')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Buton Yazısı')),
                ('button_url', models.CharField(blank=True, max_length=220, verbose_name='Buton Linki')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.managedpage', verbose_name='Sayfa')),
            ],
            options={
                'verbose_name': 'Sayfa Bölümü',
                'verbose_name_plural': 'Sayfa Bölümleri',
                'ordering': ['order', 'title'],
            },
        ),
    ]
