# Generated by Django 5.2.8 on 2026-05-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_managedpage_managedpagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_url',
            field=models.CharField(blank=True, help_text='Örn: /projeler/orman-bilgi-sistemi/', max_length=220, verbose_name='Detay Linki'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, upload_to='projects/', verbose_name='Kart Görseli'),
        ),
        migrations.AddField(
            model_name='service',
            name='detail_url',
            field=models.CharField(blank=True, help_text='Örn: /hizmetler/cografi-bilgi-sistemleri/', max_length=220, verbose_name='Detay Linki'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, upload_to='services/', verbose_name='Kart Görseli'),
        ),
    ]
