# Generated by Django 5.2.8 on 2025-11-23 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('tc_kimlik', models.CharField(max_length=11, verbose_name='TC Kimlik No')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('school', models.CharField(max_length=150, verbose_name='Okul')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='Bölüm')),
                ('notes', models.TextField(blank=True, verbose_name='Açıklama / Not')),
                ('status', models.CharField(choices=[('PENDING', 'İncelemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tc_kimlik', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='InternLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField(verbose_name='Günlük Özeti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='internship.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_logs', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Puan')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='internship.internlog')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
