# Generated by Django 5.2.8 on 2025-11-24 17:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=30, verbose_name='Soyad')),
                ('tc_no', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik numarası 11 haneli ve sadece rakamlardan oluşmalıdır.', regex='^\\d{11}$')], verbose_name='TC Kimlik No')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('school', models.CharField(max_length=100, verbose_name='Okul')),
                ('department', models.CharField(max_length=100, verbose_name='Bölüm')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='Sınıf')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Telefon numarası 10-11 haneli olmalıdır.', regex='^\\d{10,11}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'İncelemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tc_kimlik',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='TC Kimlik numarası 11 haneli ve sadece rakamlardan oluşmalıdır.', regex='^\\d{11}$')], verbose_name='TC Kimlik No'),
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Gün')),
                ('summary', models.TextField(verbose_name='Günlük Özeti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='internship.internapplication', verbose_name='Staj Başvurusu')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Puan')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='internship.dailylog', verbose_name='Günlük')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Değerlendiren Personel')),
            ],
        ),
    ]
