# Generated by Django 5.2.8 on 2025-11-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_internapplication_alter_application_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('target', models.CharField(choices=[('ALL', 'Tüm kullanıcılar'), ('INTERN', 'Stajyerler'), ('STAFF', 'Personel')], default='ALL', max_length=10, verbose_name='Hedef Kitle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Yayın Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Yayın Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-created_at'],
            },
        ),
    ]
