# Generated by Django 5.2.8 on 2026-03-31 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internapplication',
            name='account_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hesap Oluşturulma'),
        ),
        migrations.AddField(
            model_name='internapplication',
            name='credentials_sent',
            field=models.BooleanField(default=False, verbose_name='Bilgiler iletildi'),
        ),
        migrations.AddField(
            model_name='internapplication',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intern_application', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturulan Kullanıcı'),
        ),
    ]
