# Generated by Django 5.2.8 on 2026-05-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_internapplication_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='task_focus',
            field=models.CharField(blank=True, max_length=120, verbose_name='Odak Görev'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='tomorrow_plan',
            field=models.TextField(blank=True, verbose_name='Yarınki Plan'),
        ),
    ]
