# Generated by Django 5.2.8 on 2026-05-05 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_dailylog_task_focus_dailylog_tomorrow_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Mesaj')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='intern_messages/', verbose_name='Ek / Görsel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Zamanı')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='internship.internapplication', verbose_name='Stajyer Eşleşmesi')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_messages', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Staj Mesajı',
                'verbose_name_plural': 'Staj Mesajları',
                'ordering': ['created_at'],
            },
        ),
    ]
