# Generated by Django 5.2.8 on 2026-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Okunma Zamanı'),
        ),
    ]
