# Generated by Django 5.2.8 on 2026-05-06 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_application_history(apps, schema_editor):
    InternApplication = apps.get_model("internship", "InternApplication")
    ApplicationStatusHistory = apps.get_model("internship", "ApplicationStatusHistory")
    for application in InternApplication.objects.all():
        if not ApplicationStatusHistory.objects.filter(application=application).exists():
            ApplicationStatusHistory.objects.create(
                application=application,
                actor=None,
                from_status="",
                to_status=application.status,
                note="Mevcut kayıt için geçmiş başlangıcı otomatik oluşturuldu.",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0011_personneltask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=80, verbose_name='Form')),
                ('path', models.CharField(max_length=240, verbose_name='Yol')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Veri')),
                ('errors', models.JSONField(blank=True, default=dict, verbose_name='Hatalar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Zamanı')),
            ],
            options={
                'verbose_name': 'Form Hata Kaydı',
                'verbose_name_plural': 'Form Hata Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='attachment_kind',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ek Türü'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Düzenlenme'),
        ),
        migrations.AddField(
            model_name='internapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Red Nedeni'),
        ),
        migrations.AddField(
            model_name='internapplication',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Durum Güncelleme'),
        ),
        migrations.AddField(
            model_name='personneltask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma'),
        ),
        migrations.AddField(
            model_name='personneltask',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi'),
        ),
        migrations.AddField(
            model_name='personneltask',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=10, verbose_name='Öncelik'),
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=10, verbose_name='Eski Durum')),
                ('to_status', models.CharField(max_length=10, verbose_name='Yeni Durum')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Zamanı')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='internship.internapplication', verbose_name='Staj Başvurusu')),
            ],
            options={
                'verbose_name': 'Başvuru Geçmişi',
                'verbose_name_plural': 'Başvuru Geçmişi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('intern_agreement', 'Staj Sözleşmesi'), ('daily_form', 'İmzalı Günlük Formu'), ('report', 'Staj Raporu'), ('presentation', 'Sunum Dosyası')], max_length=30, verbose_name='Belge Türü')),
                ('file', models.FileField(upload_to='intern_documents/', verbose_name='Belge Dosyası')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('approved', 'Onaylandı'), ('missing', 'Eksik')], default='pending', max_length=10, verbose_name='Durum')),
                ('personnel_note', models.TextField(blank=True, verbose_name='Personel Notu')),
                ('reupload_requested', models.BooleanField(default=False, verbose_name='Tekrar Yükleme İstendi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İncelenme')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='internship.internapplication', verbose_name='Staj Başvurusu')),
            ],
            options={
                'verbose_name': 'Staj Belgesi',
                'verbose_name_plural': 'Staj Belgeleri',
                'ordering': ['category', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='Yazan')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='internship.personneltask', verbose_name='Görev')),
            ],
            options={
                'verbose_name': 'Görev Yorumu',
                'verbose_name_plural': 'Görev Yorumları',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(backfill_application_history, migrations.RunPython.noop),
    ]
