# Generated by Django 5.2.8 on 2026-05-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0013_backfill_application_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='identity_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='TC Kimlik No'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='leave_entitlement_days',
            field=models.DecimalField(decimal_places=1, default=56, max_digits=5, verbose_name='Izin Hakki (Gun)'),
        ),
        migrations.CreateModel(
            name='PersonnelLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('identity_number', models.CharField(blank=True, max_length=11, verbose_name='TC Kimlik No')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='Unvan')),
                ('leave_type', models.CharField(choices=[('annual', 'Yillik'), ('excuse', 'Mazeret'), ('birth', 'Dogum'), ('unpaid', 'Ucretsiz'), ('hourly', 'Saatlik')], max_length=20, verbose_name='Izin Turu')),
                ('start_date', models.DateField(verbose_name='Baslangic')),
                ('end_date', models.DateField(verbose_name='Bitis')),
                ('duration_value', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Sure')),
                ('duration_unit', models.CharField(default='gun', max_length=10, verbose_name='Sure Birimi')),
                ('return_date', models.DateField(verbose_name='Goreve Donus Tarihi')),
                ('reason', models.CharField(max_length=255, verbose_name='Gerekce')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adres')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandi'), ('rejected', 'Reddedildi')], default='pending', max_length=12, verbose_name='Onay')),
                ('status_note', models.TextField(blank=True, verbose_name='Durum Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Incelenme')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='internship.personnelprofile', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Personel Izin Talebi',
                'verbose_name_plural': 'Personel Izin Talepleri',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
