# Generated by Django 5.2.8 on 2026-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0014_personnelprofile_identity_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internapplication',
            name='profile_avatar',
            field=models.FileField(blank=True, upload_to='profile_avatars/interns/', verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='profile_avatar',
            field=models.FileField(blank=True, upload_to='profile_avatars/personnel/', verbose_name='Profil Fotoğrafı'),
        ),
    ]
