# Generated by Django 5.2.8 on 2026-05-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0015_internapplication_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Eski Başvuru', 'verbose_name_plural': 'Eski Başvurular'},
        ),
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Staj Günlüğü', 'verbose_name_plural': 'Staj Günlükleri'},
        ),
        migrations.AlterModelOptions(
            name='internapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staj Başvurusu', 'verbose_name_plural': 'Staj Başvuruları'},
        ),
        migrations.AlterModelOptions(
            name='internlog',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Eski Staj Günlüğü', 'verbose_name_plural': 'Eski Staj Günlükleri'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-date'], 'verbose_name': 'Günlük Kaydı', 'verbose_name_plural': 'Günlük Kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='logreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Eski Günlük Değerlendirmesi', 'verbose_name_plural': 'Eski Günlük Değerlendirmeleri'},
        ),
        migrations.AlterModelOptions(
            name='personnelleaverequest',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': 'Personel İzin Talebi', 'verbose_name_plural': 'Personel İzin Talepleri'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Günlük Değerlendirmesi', 'verbose_name_plural': 'Günlük Değerlendirmeleri'},
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='duration_unit',
            field=models.CharField(default='gun', max_length=10, verbose_name='Süre Birimi'),
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='duration_value',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Süre'),
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='end_date',
            field=models.DateField(verbose_name='Bitiş'),
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Yıllık'), ('excuse', 'Mazeret'), ('birth', 'Doğum'), ('unpaid', 'Ücretsiz'), ('hourly', 'Saatlik')], max_length=20, verbose_name='İzin Türü'),
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Gerekçe'),
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='return_date',
            field=models.DateField(verbose_name='Göreve Dönüş Tarihi'),
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İncelenme'),
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='start_date',
            field=models.DateField(verbose_name='Başlangıç'),
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=12, verbose_name='Onay'),
        ),
        migrations.AlterField(
            model_name='personnelleaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='leave_entitlement_days',
            field=models.DecimalField(decimal_places=1, default=56, max_digits=5, verbose_name='İzin Hakkı (Gün)'),
        ),
    ]
